language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
    - models

sudo: required
go:
  - 1.13.x

env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.cn

branches:
  only:
    - master

install:
  - echo '====download models start===='
  - wget "http://thulac.thunlp.org/source/Models_v1_v2(v1_2).zip"
  - unzip -d models "Models_v1_v2(v1_2).zip"
  - echo '====download models finish===='

script:
  - go test -v .

