language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

go:
  - "1.13.5"

env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.cn

branches:
  only:
    - master

install:
  - wget "http://thulac.thunlp.org/source/Models_v1_v2(v1_2).zip"
  - unzip -d models -o "Models_v1_v2(v1_2).zip"
  - ls -l -a -h

script:
  - go version && go test -timeout 30s github.com/Tsingxiao/thulacgo  -v -count=1

