language: go
go:
  - "1.13.5"

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

sudo: required

env:
  - GO111MODULE=on

branches:
  only:
    - master

install:
  - echo '=============install==============='
#  - bash scripts/models.sh

script:
  - go test -v ./... -count=1
  - echo ====== test result is $? ========
