language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
sudo: required
go:
  - 1.13.x

env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.cn

branches:
  only:
    - master

install:
  - ./scripts/models.sh $(pwd)

script:
  - go test -v .

