language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
    - models

install: true
sudo: required

go:
  - "1.13.5"

env:
  - GO111MODULE=on

branches:
  only:
    - master

script:
  - go env
  - bash scripts/models.sh
  - go test -count=1
