language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

go:
  - "1.13.5"

branches:
  only:
    - master

sudo: required
install:
  - wget "http://thulac.thunlp.org/source/Models_v1_v2(v1_2).zip"
  - unzip -o "Models_v1_v2(v1_2).zip"
  - ls -l -a -h
  - go env -w GO111MODULE=on
  - go env -w GOPROXY=https://goproxy.cn
  - go env


script:
  - go test -v ./... -count=1
