language: go
go:
  - "1.13.5"

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

sudo: required

env:
  - GO111MODULE=on

branches:
  only:
    - master

install:
  - echo 'intall===================='
#  - bash scripts/models.sh

script:
  - go test -v thulac_test.go -count=1
